### ISSUE TITLE
Bạn nên sử dụng int main() thay vì sử dụng void main() ở các bài tập tiếp theo 

### ISSUE THREAD

**Issue by m1nhn** [vidongls/Cbasic#12]
https://github.com/vidongls/Cbasic/blob/84fe862eb1949692629b269a21bce3eee718f428/BT_ham/B4_hoanvi.cpp#L9

https://www.tutorialspoint.com/difference-between-void-main-and-int-main-in-c-cplusplus

**Comment by vidongls** [comment]
dạ vâng ạ
