### ISSUE TITLE
Nếu giả sử trường hợp mình nhập năm  2022. Tuổi mình sẽ bị âm thì bạn tính thế nào ? Và cái tiếp theo nếu như giả sử mình muốn nhập lại tuổi vì mình nhập là âm. Nhưng chương trình lại tự động exit(), thì làm thế nào đây ? 

### ISSUE THREAD

**Issue by m1nhn** [vidongls/Cbasic#13]
https://github.com/vidongls/Cbasic/blob/84fe862eb1949692629b269a21bce3eee718f428/BT_ham/B5_tinhtuoi.cpp#L11-L13
https://github.com/vidongls/Cbasic/blob/84fe862eb1949692629b269a21bce3eee718f428/BT_ham/B5_tinhtuoi.cpp#L4-L6

**Comment by vidongls** [comment]
e sửa r ạ
