### ISSUE TITLE
Thông thường ở đây nên khởi tạo 2 giá trị min, max với một giá trị nào đó. Bạn thử suy nghĩ xem nên gán với giá trị nào. 

### ISSUE THREAD

**Issue by m1nhn** [vidongls/Cbasic#15]
https://github.com/vidongls/Cbasic/blob/7431a66734ff4ba35774273723757251610a82b8/BT_ham/B2_minmax.cpp#L6-L7

**Comment by vidongls** [comment]
nên gán min =0; max =0

**Comment by vidongls** [comment]
gán min =  giá cực đại max = giá trị cực tiểu ạ
