### ISSUE TITLE
Với lại nếu bạn k khởi tạo giá trị của min hoặc max thì rất là vô lý nếu như k biết được hai giá trị nào đang so sánh với nhau 

### ISSUE THREAD

**Issue by m1nhn** [vidongls/Cbasic#16]
https://github.com/vidongls/Cbasic/blob/7431a66734ff4ba35774273723757251610a82b8/BT_ham/B2_minmax.cpp#L15

**Comment by vidongls** [comment]
dạ e gán ở trên r ạ;
	if (i == 1)
		{
			max = a;
			min = a;
		}

**Comment by m1nhn** [comment]
Vậy bạn có thể đưa việc gán này ra ngoài. Hoặc bạn chỉ cần gọn gàng rằng : ` max = a[1]; min = a[1];`

**Comment by vidongls** [comment]
Mình không dùng mảng mà a

**Comment by m1nhn** [comment]
Nếu theo quan điểm của mình thì bạn sẽ khởi tạo `max = -9999999;` và `min = 100000000;`.

**Comment by vidongls** [comment]
dạ.. cách của e có sao k ạ

**Comment by m1nhn** [comment]
Thực ra k sao cả nhưng mà thông thường họ hay làm ngược như vậy. Họ gán giá trị max cho giá trị vô cùng bé và giá trị min thì làm lại ngược nhưu vậy

**Comment by vidongls** [comment]
dạ vâng ạ ...
