### ISSUE TITLE
Số âm có thể là số chính phương k bạn ? 

### ISSUE THREAD

**Issue by m1nhn** [vidongls/Cbasic#17]
https://github.com/vidongls/Cbasic/blob/94034aa0c9ac8c2a907ef8e205527fca4ae87d94/BT_ham/bt_ham_nangcao/bai3.cpp#L9

**Comment by vidongls** [comment]
dạ có nguyên dương, nguyên âm và số 0

**Comment by m1nhn** [comment]
Số ÂM có thể là số chính phương không bạn ?

**Comment by vidongls** [comment]
Khoong a
