### ISSUE TITLE
Liệu return có thể trả về được mấy giá trị ? 1 hay nhiều giá trị ? 

### ISSUE THREAD

**Issue by m1nhn** [vidongls/Cbasic#2]
https://github.com/vidongls/Cbasic/blob/84fe862eb1949692629b269a21bce3eee718f428/BT_ham/ly_thuyet.txt#L7

**Comment by vidongls** [comment]
Khi sử dụng câu lệnh return, hàm chỉ có thể trả về một giá trị duy nhất.
