### ISSUE TITLE
Mảng động và mảng tĩnh đều dùng chung bộ nhớ hay lượng bộ nhớ được cấp phát tuỳ vào từng loại mảng là như nhau ???

### ISSUE THREAD

**Issue by m1nhn** [vidongls/Cbasic#20]
https://github.com/vidongls/Cbasic/blob/0e380676a4495e94ab2907ef62e738c67ee77f34/Bt_mang/lythuyet.txt#L4

**Comment by vidongls** [comment]
Câu này e chưa rõ .. A giải thích dc k ạ :((

**Comment by m1nhn** [comment]
Ví dụ trường hợp mảng động thì số lượng phần tử có thể thay đổi được thì bộ nhớ cấp ra sẽ được thay đổi và đạt tối ưu 
Còn đâu đối với trường hợp mảng tĩnh các bạn khai báo tới 1000 phần tử nhưng mảng nhập vào chỉ có khoảng từ 10-40 là max rồi thì sẽ dẫn đến việc bộ nhớ sẽ bị thừa (không được dùng). Đó là cái mà mình đang muốn hỏi bạn trong câu hỏi này
