### ISSUE TITLE
Vậy giả sử hàm đó chưa được định nghĩa hoặc là hàm k có tham số cần truyền vào thì làm thế nào đây ta ? 

### ISSUE THREAD

**Issue by m1nhn** [vidongls/Cbasic#5]
https://github.com/vidongls/Cbasic/blob/84fe862eb1949692629b269a21bce3eee718f428/BT_ham/ly_thuyet.txt#L20

**Comment by vidongls** [comment]
Dạ. Cần hàm được định nghĩa 
Nếu hàm có tham số thì truyền vào đúng tham số.
Hàm không có tham số thì không cần truyền vào.
